### PR TITLE
handle redirects manually

### LINKED ISSUE #96: Artifact Downloading Fails on Github Redirect
### Environment
* Erlang version (erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell): `19`
* Elixir version (elixir -v): `1.4.2`
* Operating system: Mac OS 10.12.3
* Nerves Environment Info: Trying to build the blinky example app for `rpi` target

```
|nerves_bootstrap| Environment Package List

  Pkg:      nerves_system_br
  Vsn:      0.9.4
  Type:     system_platform
  Provider: [{Nerves.Package.Providers.HTTP, []}, {Nerves.Package.Providers.Docker, []}]

  Pkg:      nerves_system_rpi
  Vsn:      0.11.0
  Type:     system
  Provider: [{Nerves.Package.Providers.HTTP, []}, {Nerves.Package.Providers.Docker, []}]

  Pkg:      nerves_toolchain_armv6_rpi_linux_gnueabi
  Vsn:      0.10.0
  Type:     toolchain
  Provider: [{Nerves.Package.Providers.HTTP, []}, {Nerves.Package.Providers.HTTP, []}]

  Pkg:      nerves_toolchain_ctng
  Vsn:      0.9.0
  Type:     toolchain_platform
  Provider: [{Nerves.Package.Providers.HTTP, []}, {Nerves.Package.Providers.Docker, []}]

|nerves_bootstrap| Loadpaths Start

|nerves_bootstrap| Env Start

|nerves_bootstrap| Env End

|nerves_bootstrap| Environment Variable List
  target:     rpi
  toolchain:  /Users/hqmq/.nerves/artifacts/nerves_toolchain_armv6_rpi_linux_gnueabi-0.10.0.darwin-x86_64
  system:     /Users/hqmq/.nerves/artifacts/nerves_system_rpi-0.11.0.armv6_rpi_linux_musl
  app:        /Users/hqmq/code/tmp/nerves-examples/blinky

|nerves_bootstrap| Loadpaths End
```

### Current behavior

```
mmmries-pro:blinky$ MIX_TARGET=rpi mix do deps.get, firmware, firmware.burn
Env
  MIX_TARGET:   rpi
  MIX_ENV:      dev

Running dependency resolution...
Dependency resolution completed:
  nerves_system_rpi 0.11.0
  nerves_toolchain_armv6_rpi_linux_gnueabi 0.10.0
* Getting nerves (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves-0.5.0.tar)
  Fetched package
* Getting nerves_runtime (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_runtime-0.1.1.tar)
  Fetched package
* Getting nerves_system_rpi (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_system_rpi-0.11.0.tar)
  Fetched package
* Getting nerves_leds (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_leds-0.7.0.tar)
  Fetched package
* Getting nerves_system_br (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_system_br-0.9.4.tar)
  Fetched package
* Getting nerves_toolchain_armv6_rpi_linux_gnueabi (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_toolchain_armv6_rpi_linux_gnueabi-0.10.0.tar)
  Fetched package
* Getting nerves_toolchain_ctng (Hex package)
  Checking package (https://repo.hex.pm/tarballs/nerves_toolchain_ctng-0.9.0.tar)
  Fetched package
* Getting elixir_make (Hex package)
  Checking package (https://repo.hex.pm/tarballs/elixir_make-0.4.0.tar)
  Fetched package
* Getting gen_stage (Hex package)
  Checking package (https://repo.hex.pm/tarballs/gen_stage-0.11.0.tar)
  Fetched package
* Getting distillery (Hex package)
  Checking package (https://repo.hex.pm/tarballs/distillery-1.2.2.tar)
  Fetched package
==> distillery
Compiling 18 files (.ex)
Generated distillery app
==> nerves
Compiling 25 files (.ex)
Generated nerves app
==> nerves_system_br
Generated nerves_system_br app
==> nerves_toolchain_ctng
Compiling 2 files (.ex)
Generated nerves_toolchain_ctng app
==> nerves_toolchain_armv6_rpi_linux_gnueabi
Compiling 1 file (.ex)
Generated nerves_toolchain_armv6_rpi_linux_gnueabi app
|Elixir.Nerves.Package.Providers.HTTP| Downloading Artifact nerves_toolchain_armv6_rpi_linux_gnueabi-0.10.0.darwin-x86_64.tar.xz
  From Location:
    https://github.com/nerves-project/toolchains/releases/download/v0.10.0/nerves_toolchain_armv6_rpi_linux_gnueabi-0.10.0.darwin-x86_64.tar.xz

|Elixir.Nerves.Package.Providers.HTTP| No Available Locations

|Elixir.Nerves.Package.Providers.HTTP| Downloading Artifact nerves_toolchain_armv6_rpi_linux_gnueabi-0.10.0.darwin-x86_64.tar.xz
  From Location:
    https://github.com/nerves-project/toolchains/releases/download/v0.10.0/nerves_toolchain_armv6_rpi_linux_gnueabi-0.10.0.darwin-x86_64.tar.xz

|Elixir.Nerves.Package.Providers.HTTP| No Available Locations

==> nerves_system_rpi
Generated nerves_system_rpi app
|Elixir.Nerves.Package.Providers.HTTP| Downloading Artifact nerves_system_rpi-0.11.0.armv6_rpi_linux_musl.tar.gz
  From Location:
    https://github.com/nerves-project/nerves_system_rpi/releases/download/v0.11.0/nerves_system_rpi-v0.11.0.tar.gz

|Elixir.Nerves.Package.Providers.HTTP| No Available Locations

could not compile dependency :nerves_system_rpi, "mix compile" failed. You can recompile this dependency with "mix deps.compile nerves_system_rpi", update it with "mix deps.update nerves_system_rpi" or clean it with "mix deps.clean nerves_system_rpi"
```

### Expected behavior

The downloads should succeed so that my firmware bundle can be built correctly

### PR DESCRIPTION
**Pull request by mmmries**
An attempt to fix #96

In the [erlang 19.3 release](http://erlang.org/download/otp_src_19.3.readme) there was a change made to include the port number in the host header during a redirect. This breaks the signing that happens for AWS download links. The broken redirect then manifests as an error [downloading artifacts](https://github.com/nerves-project/nerves/issues/96).

A minimal reproducible on the error and a way to verify the fix is the run: `$ mix run -e 'Nerves.Utils.HTTPClient.start_link |> elem(1) |> Nerves.Utils.HTTPClient.get("https://github.com/nerves-project/toolchains/releases/download/v0.10.0/nerves_toolchain_armv6_rpi_linux_gnueabi-0.10.0.darwin-x86_64.tar.xz") |> IO.inspect'`

/cc @mobileoverlord @ghitchens

### CODE REVIEW

**Comment by mmmries** [comment]
Should I handle avoiding infinite redirects here?

**Comment by mobileoverlord** [comment]
Yeah, we should probably track in the state and redirect a maximum number of times. I think 5 or 10 is more than reasonable

**Comment by mmmries** [comment]
Added a commit that handles redirect loops. Tested it with this:

```
$ mix run -e 'Nerves.Utils.HTTPClient.start_link |> elem(1) |> Nerves.Utils.HTTPClient.get("http://httpbin.org/absolute-redirect/6") |> IO.inspect'
{:error, :too_many_redirects}
```

BTW if anyone has a good way to do unit tests one these I would love to add coverage, its just one of those things that I don't know a good pattern for other than dependency injection which feels like too much overhead in this case.

**Comment by GregMefford** [comment]
We've been holding our breath for a while on the Nerves testing front because we're very close to having Nerves ready to better support running on either host or target, which will make testing on the host a lot easier. I definitely agree that we should work on better test coverage but it's pretty tricky in a cross-compiling scenario. 😅

File: lib/nerves/utils/http_client.ex [hunk 1]
```diff
@@ -76,6 +81,14 @@ defmodule Nerves.Utils.HTTPClient do
     {:noreply, %{s | filename: "", content_length: 0, buffer: "", buffer_size: 0, url: nil}}
   end
 
+  def handle_info({:http, {_ref, {{_, status_code, _}, headers, _body}}}, s) do
```
Comment (ericmj) [inline lib/nerves/utils/http_client.ex]: You should check the status_code since the location header can be included in responses that are not actually redirects.

Comment (ericmj) [inline lib/nerves/utils/http_client.ex]: This is how Hex handles redirects: https://github.com/hexpm/hex/blob/master/lib/hex/http.ex#L60-L87

**Comment by mmmries** [comment]
I added a commit that pattern matches on the `status_code` before attempting the redirect logic. Verified that this still fails for redirect loops and succeeds for downloading the release artifacts from github/aws.

Thanks for the tip @ericmj. I didn't know that you could get back location headers for other responses

**Comment by mobileoverlord** [comment]
This looks good, going to merge it in and release. Thanks @mmmries  @voltone and @ericmj 
:bowtie: ❤️

**Comment by voltone** [comment]
FWIW, Erlang/OTP 19.3.1 is supposed to fix the regression in `httpc`, even though it is not explicitly mentioned in the release notes. Will verify once it lands in Homebrew...

**Comment by mobileoverlord** [comment]
Fool me once...
